_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 5ea390e6-7f26-4f29-9b68-7a6c1a3fe7cd
name: 'Waterfall Handbook'
mail: admin@waterfall.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
